name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "release"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Decode keystore
        run: |
          echo "${{ secrets.ENCODED_RELEASE_KEYSTORE }}" | base64 -d > ./app/key.jks

      - name: Set up gradle.properties
        run: |
          echo "KEYSTORE_FILE=./key.jks" >> local.properties
          echo "KEYSTORE_PASSWORD=${{ secrets.RELEASE_KEYSTORE_STORE_PASSWORD }}" >> local.properties
          echo "KEY_ALIAS=${{ secrets.RELEASE_KEYSTORE_ALIAS }}" >> local.properties
          echo "KEY_PASSWORD=${{ secrets.RELEASE_KEYSTORE_ALIAS_PASSWORD }}" >> local.properties
          echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" >> local.properties

      - name: Set VERSION_CODE with offset and log it
        run: |
          VERSION_CODE=$(( ${{ github.run_number }} + 13 ))
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "VERSION_CODE is set to: $VERSION_CODE"

      - name: Generate AAB
        run: ./gradlew :app:bundleRelease
        env:
          VERSION_CODE: ${{ env.VERSION_CODE }}
