name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "release"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Create amplifyconfiguration.json (Android)
        run: |
          mkdir -p app/src/main/res/raw
          cat <<EOF > app/src/main/res/raw/amplifyconfiguration.json
          {
              "aws_project_region": "ap-northeast-1",
              "auth": {
                  "plugins": {
                      "awsCognitoAuthPlugin": {
                              "CognitoUserPool": {
                              "Default": {
                                  "PoolId": "${{ secrets.AWS_AMPLIFY_COGNITO_POOL_ID }}",
                                  "AppClientId": "${{ secrets.AWS_AMPLIFY_COGNITO_APP_CLIENT_ID }}",
                                  "Region": "${{ secrets.AWS_AMPLIFY_COGNITO_REGION }}"
                              }
                          },
                          "Auth": {
                              "Default": {
                                  "authenticationFlowType": "USER_SRP_AUTH"
                              }
                          }
                      }
                  }
              }
          }
          EOF

      - name: Create secrets directory
        run: |
          mkdir secrets

      - name: Decode Keystore
        run: echo '${{ secrets.ENCODED_RELEASE_KEYSTORE }}' | base64 --decode > playstore.keystore

      - name: Copy Keystore
        run: |
          cp playstore.keystore secrets/playstore.keystore

      - name: Create amplifyconfiguration.json (Android)
        run: |
          mkdir -p app/src/main/res/raw
          cat <<EOF > app/src/main/res/raw/amplifyconfiguration.json
          {
            "aws_project_region": "ap-northeast-1",
            "auth": {
                "plugins": {
                  "awsCognitoAuthPlugin": {
                        "CognitoUserPool": {
                          "Default": {
                              "PoolId": "${{ secrets.AWS_AMPLIFY_COGNITO_POOL_ID }}",
                              "AppClientId": "${{ secrets.AWS_AMPLIFY_COGNITO_APP_CLIENT_ID }}",
                              "Region": "${{ secrets.AWS_AMPLIFY_COGNITO_REGION }}"
                          }
                        },
                        "Auth": {
                          "Default": {
                              "authenticationFlowType": "USER_SRP_AUTH"
                          }
                      }
                  }
                }
            }
          }
          EOF

      - name: Set VERSION_CODE with offset and log it
        run: |
          VERSION_CODE=$(( ${{ github.run_number }} + 13 ))
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "VERSION_CODE is set to: $VERSION_CODE"

      - name: Generate AAB
        run: ./gradlew :app:bundleRelease
        env:
          KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          KEYSTORE_ALIAS_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_ALIAS_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_STORE_PASSWORD }}
          VERSION_CODE: ${{ github.run_number }}
