name: Deploy
on:
  push:
    branches: ["release"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Create secrets directory
        run: |
          mkdir secrets

      - name: Decode Keystore
        run: echo '${{ secrets.ENCODED_RELEASE_KEYSTORE }}' | base64 --decode > playstore.keystore

      - name: Copy Keystore
        run: |
          cp playstore.keystore secrets/playstore.keystore

      - name: Generate AAB
        run: ./gradlew :app:bundleRelease
        env:
          KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          KEYSTORE_ALIAS_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_ALIAS_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_STORE_PASSWORD }}

      - name: Create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to Play Store
        id: deploy
        uses: r0adkll/upload-google-play@v1.1.2
        with:
          serviceAccountJson: service_account.json
          packageName: com.studiomk.matool
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
